[package]
name = "prioritized-metered-channel"
version = "0.6.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Channels with built-in observability and optional message priorizitazion"
repository = "https://github.com/paritytech/orchestra.git"
license = "MIT OR Apache-2.0"

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
async-channel = { version = "1.8.0", optional = true }
derive_more = { version = "1.0", features = ["display"] }
tracing = "0.1.35"
thiserror = "1.0.31"
crossbeam-queue = "0.3.5"
nanorand = { version = "0.7.0", default-features = false, features = [
  "wyrand",
] }
coarsetime = "^0.1.22"

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
assert_matches = "1.5"
env_logger = "0.9"
log = "0.4"
tracing = { version = "0.1.35", features = ["log"] }

[features]
default = ["async_channel"]
async_channel = ["dep:async-channel"]
futures_channel = []
